CREATE database DATABASE03;
USE DATABASE03;
 CREATE TABLE SUB_QUERY(
 SR_NO INT,
 CUS_ID INT,
 AMOUNT INT,
 MODE varchar(50)
 
 
 );
 
 SELECT * FROM SUB_QUERY;
 
 
 INSERT INTO SUB_QUERY (SR_NO,CUS_ID,AMOUNT,MODE)
 values
 (1,101,60,"CASH"),
 (2,102,30,"CREDIT CARD"),
 (3,103,110,"CASH"),
 (4,104,70,"MOBILE PAYMENT"),
 (5,105,80,"CASH");
 
 
 SELECT * FROM SUB_QUERY;
 
 SELECT avg(AMOUNT)
from SUB_QUERY; 


 select* FROM SUB_QUERY
 WHERE AMOUNT>=(select  avg(AMOUNT) FROM SUB_QUERY);
 
 
